version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:1323" # Expose host port 8080 to container port 1323
    environment:
      SERVER_PORT: 1323
      DATABASE_URL: hung:hung123456!@tcp(db:3306)/kart_challenge_db?parseTime=true
      REDIS_ADDR: redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
